name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install latest mdbook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Build mdBook
      run: |
        echo "Building the book"
        mdbook build
        echo "Zipping the book"
        zip -r github-actions.zip pierce
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: pierce/github-pages.zip
    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        artifact-name: github-pages